base_path: /dataset/evqa
image_path: datasets/real_images/Downside_Abbey.jpg
kb_json_name: encyclopedic_kb_wiki.json
text_query: Who built the choir at this abbey?
k_value: 10
m_value: 10
alpha: 0.9
first_image_only: false
use_tfidf_filter: false
tfidf_ratio: 0.5
image_device: 0
# Device placement
bge_device: 1
nli_device: 2
nli_batch_size: 32
dataset_csv: /dataset/evqa/test.csv
id2name_paths:
  - /dataset/inaturalist/train_id2name.json
dataset_image_root: /dataset/inaturalist
dataset_google_root: /dataset/landmarks

dataset_start: 0
dataset_end: 5750
#dataset_start: 0
#dataset_end: 4750

text_encoder_model: facebook/contriever
segment_level: section # "section", "paragraph" or "sentence"
chunk_size: 1024
#bge_model: BAAI/bge-reranker-v2-m3
bge_model: BAAI/bge-reranker-large
bge_max_length: 512 # ✅ 추가
bge_conf_threshold: 0.3
nli_model: tasksource/deberta-base-long-nli
#nli_model: MoritzLaurer/DeBERTa-v3-large-mnli-fever-anli-ling-wanli
nli_max_length: 1024
nli_max_cluster: 3
nli_e_min: 0.4 #Entailment가 이거보다 낮음 탈락 
nli_margin: 0.2 #ent-con 점수가 이거보다 낮으면 탈락 #0.0 #기존 0.1
nli_tau: 0.20 #α * 내포 - β * 모순 점수가 이거보다 낮음 탈락, 지금αβ는 둘다 1
nli_lambda: 0.7 

# Reranker settings
rerankers:
  contriever: false
  jina_m0: false
  bge: true
